#pragma once
typedef enum {
	LOG_OUTPUT_POLICY_NONE,
	LOG_OUTPUT_POLICY_FILE,
	LOG_OUTPUT_POLICY_STDOUT,
	LOG_OUTPUT_POLICY_BOTH = LOG_OUTPUT_POLICY_FILE | LOG_OUTPUT_POLICY_STDOUT
}LOG_OUTPUT_POLICY;

void logger_init(LOG_OUTPUT_POLICY policy);
